version: '3.8'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=10051006
      - POSTGRES_DB=forum

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "criomore1331@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "10051006"
    ports:
      - "80:80"
    depends_on:
      - postgres
